### ISSUE TITLE
Fails to start on Arch linux on GNOME 45

### ISSUE THREAD

**Issue by joske** [Aryan20/Logomenu#56]
Arch linux just updated to GNOME 45, and several extensions got broken, this one included. Strange as it's supposed to work in 45. It complains about `Constants.SymbolicDistroIcons`. Looking at the code, not clear to me why this would not work.

Maybe arch hasn't updated all packages yet, but putting this here so it may help others.

With this small change in `extension.js` in `setIconImage()` it starts up:
```javascript
      // if(isSymbolic) {
      //     isStartHereSymbolic = Constants.SymbolicDistroIcons[iconIndex].PATH === 'start-here-symbolic';
      //     iconPath = this._extension.path + Constants.SymbolicDistroIcons[iconIndex].PATH;
      // } else {
      iconPath =
        this._extension.path + Constants.ColouredDistroIcons[iconIndex].PATH;
      // }
```

**Comment by joske** [comment]
Update: after it started up once with the above patch, putting back the original code and restarting also makes the original code work again.

**Comment by Aryan20** [comment]
It could be due to the way Icons are picked now. They were all in one area earlier, but as part of re-write efforts, they were split into two zones. Maybe it was using new code but was looking in the old constants file (The one with icon names), 
I think a restart after the update would solve this issue, but can only know when my machine updates :)
Thanks for bringing it up though!

**Comment by Aryan20** [comment]
Closing this as I think it was just flaky behaviour.

**Comment by Aryan20** [comment]
Found the error. It was a problem.
